/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.sheintap;

import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Mrx
 */
public class InterfazGeneral extends javax.swing.JFrame {

    
    
    /**
     *
     */
    public InterfazGeneral() {
        
        initComponents();
        
         
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/company.png")).getImage());
        PanelPrincipal.setOpaque(false);
        
        
       
        
        
    }
    
    
    
    
    
    private void buttons(){
    
       
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelateral = new org.edisoncor.gui.panel.PanelImage();
        userlateral = new org.edisoncor.gui.panel.PanelImage();
        panelEmpleado = new org.edisoncor.gui.panel.PanelImage();
        buttonclientes = new javax.swing.JLabel();
        PuestosPanIm1 = new org.edisoncor.gui.panel.PanelImage();
        buttonpedidospts = new javax.swing.JLabel();
        CiclosPanImg4 = new org.edisoncor.gui.panel.PanelImage();
        buttonCiclos = new javax.swing.JLabel();
        pngFace = new org.edisoncor.gui.panel.PanelImage();
        homebutton = new org.edisoncor.gui.panel.PanelImage();
        buttonclose = new org.edisoncor.gui.panel.PanelImage();
        minimizarGen = new org.edisoncor.gui.panel.PanelImage();
        PanelPrincipal = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-negro-abstracto-moderno_1025-213.jpg"))); // NOI18N
        panelateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userlateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N

        javax.swing.GroupLayout userlateralLayout = new javax.swing.GroupLayout(userlateral);
        userlateral.setLayout(userlateralLayout);
        userlateralLayout.setHorizontalGroup(
            userlateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        userlateralLayout.setVerticalGroup(
            userlateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        panelateral.add(userlateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, -1));

        panelEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register-Button-PNG-Image.png"))); // NOI18N
        panelEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonclientes.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        buttonclientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonclientes.setText("Clientes");
        buttonclientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                buttonclientesMouseMoved(evt);
            }
        });
        buttonclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonclientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonclientesMouseEntered(evt);
            }
        });
        panelEmpleado.add(buttonclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 46));

        panelateral.add(panelEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 203, -1, -1));

        PuestosPanIm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register-Button-PNG-Image.png"))); // NOI18N
        PuestosPanIm1.setMinimumSize(new java.awt.Dimension(100, 100));
        PuestosPanIm1.setPreferredSize(new java.awt.Dimension(160, 46));

        buttonpedidospts.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        buttonpedidospts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonpedidospts.setText("Pedidos");
        buttonpedidospts.setMaximumSize(new java.awt.Dimension(105, 15));
        buttonpedidospts.setMinimumSize(new java.awt.Dimension(105, 15));
        buttonpedidospts.setPreferredSize(new java.awt.Dimension(105, 15));
        buttonpedidospts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonpedidosptsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PuestosPanIm1Layout = new javax.swing.GroupLayout(PuestosPanIm1);
        PuestosPanIm1.setLayout(PuestosPanIm1Layout);
        PuestosPanIm1Layout.setHorizontalGroup(
            PuestosPanIm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PuestosPanIm1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonpedidospts, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PuestosPanIm1Layout.setVerticalGroup(
            PuestosPanIm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PuestosPanIm1Layout.createSequentialGroup()
                .addComponent(buttonpedidospts, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        panelateral.add(PuestosPanIm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        CiclosPanImg4.setAlignmentX(0.0F);
        CiclosPanImg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register-Button-PNG-Image.png"))); // NOI18N
        CiclosPanImg4.setPreferredSize(new java.awt.Dimension(160, 46));

        buttonCiclos.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        buttonCiclos.setText("                      Ciclos");
        buttonCiclos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCiclosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CiclosPanImg4Layout = new javax.swing.GroupLayout(CiclosPanImg4);
        CiclosPanImg4.setLayout(CiclosPanImg4Layout);
        CiclosPanImg4Layout.setHorizontalGroup(
            CiclosPanImg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CiclosPanImg4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonCiclos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CiclosPanImg4Layout.setVerticalGroup(
            CiclosPanImg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CiclosPanImg4Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(buttonCiclos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelateral.add(CiclosPanImg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, 47));

        pngFace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facepng.png"))); // NOI18N
        pngFace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pngFaceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pngFaceLayout = new javax.swing.GroupLayout(pngFace);
        pngFace.setLayout(pngFaceLayout);
        pngFaceLayout.setHorizontalGroup(
            pngFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        pngFaceLayout.setVerticalGroup(
            pngFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelateral.add(pngFace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 559, -1, -1));

        homebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home2-buton.png"))); // NOI18N
        homebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homebuttonLayout = new javax.swing.GroupLayout(homebutton);
        homebutton.setLayout(homebuttonLayout);
        homebuttonLayout.setHorizontalGroup(
            homebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        homebuttonLayout.setVerticalGroup(
            homebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelateral.add(homebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 559, -1, 40));

        getContentPane().add(panelateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 610));

        buttonclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button-close.png"))); // NOI18N
        buttonclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttoncloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout buttoncloseLayout = new javax.swing.GroupLayout(buttonclose);
        buttonclose.setLayout(buttoncloseLayout);
        buttoncloseLayout.setHorizontalGroup(
            buttoncloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        buttoncloseLayout.setVerticalGroup(
            buttoncloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(buttonclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 30, 30));

        minimizarGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button-minizar.png"))); // NOI18N
        minimizarGen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarGenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout minimizarGenLayout = new javax.swing.GroupLayout(minimizarGen);
        minimizarGen.setLayout(minimizarGenLayout);
        minimizarGenLayout.setHorizontalGroup(
            minimizarGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        minimizarGenLayout.setVerticalGroup(
            minimizarGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(minimizarGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 30, 30));

        PanelPrincipal.setOpaque(false);

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 830, 580));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/white-blue-gradient-linear-1920x1080-c2-ffffff-b0c4de-a-135-f-14.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        fondo.setMaximumSize(getPreferredSize());
        fondo.setPreferredSize(getMinimumSize());
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int x,y;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
        
    }//GEN-LAST:event_formMousePressed
    
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_formMouseDragged

    private void buttoncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttoncloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttoncloseMouseClicked
 
    private void buttonCiclosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCiclosMouseClicked
        // TODO add your handling code here:
        JpVerCiclos quincena= new JpVerCiclos();
     
        quincena.setSize(PanelPrincipal.getSize());
        quincena.setLocation(20, 10);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(quincena,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
        
        
    }//GEN-LAST:event_buttonCiclosMouseClicked

    private void pngFaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pngFaceMouseClicked
        // TODO add your handling code here:
        try{
            if(Desktop.isDesktopSupported()){
                Desktop desktop = Desktop.getDesktop();
                if(desktop.isSupported(Desktop.Action.BROWSE)){
                    desktop.browse(new URI("www.facebok.com"));
                }
            }
        }catch(URISyntaxException | IOException e){
        }
        
    }//GEN-LAST:event_pngFaceMouseClicked

    private void minimizarGenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarGenMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizarGenMouseClicked

    private void buttonclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonclientesMouseClicked
        // TODO add your handling code here:
        PanelPrincipal.setOpaque(false);
        JpClientes empleados= new JpClientes();
        empleados.setSize(PanelPrincipal.getSize());
        empleados.setLocation(6, 8);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(empleados,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        buttons();
        
    }//GEN-LAST:event_buttonclientesMouseClicked

    private void homebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebuttonMouseClicked
        // TODO add your handling code here:
        PanelPrincipal.setOpaque(false);
        JpVerTodos vertodos= new JpVerTodos();
        vertodos.setSize(PanelPrincipal.getSize());
        vertodos.setLocation(10, 8);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(vertodos,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
       
    }//GEN-LAST:event_homebuttonMouseClicked

    private void buttonpedidosptsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpedidosptsMouseClicked
        // TODO add your handling code here:
        PanelPrincipal.setOpaque(false);
        JpVerPedidosPendientes ver= new JpVerPedidosPendientes();
        ver.setSize(PanelPrincipal.getSize());
        ver.setLocation(70, 20);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(ver,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        buttons();
        
        
    }//GEN-LAST:event_buttonpedidosptsMouseClicked

    private void buttonclientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonclientesMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonclientesMouseMoved

    private void buttonclientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonclientesMouseEntered
        // TODO add your handling code here
        
        
    }//GEN-LAST:event_buttonclientesMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InterfazGeneral().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage CiclosPanImg4;
    private javax.swing.JPanel PanelPrincipal;
    private org.edisoncor.gui.panel.PanelImage PuestosPanIm1;
    private javax.swing.JLabel buttonCiclos;
    private javax.swing.JLabel buttonclientes;
    private org.edisoncor.gui.panel.PanelImage buttonclose;
    private javax.swing.JLabel buttonpedidospts;
    private javax.swing.JLabel fondo;
    private org.edisoncor.gui.panel.PanelImage homebutton;
    private org.edisoncor.gui.panel.PanelImage minimizarGen;
    private org.edisoncor.gui.panel.PanelImage panelEmpleado;
    private org.edisoncor.gui.panel.PanelImage panelateral;
    private org.edisoncor.gui.panel.PanelImage pngFace;
    private org.edisoncor.gui.panel.PanelImage userlateral;
    // End of variables declaration//GEN-END:variables
}
