/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.sheintap;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mrx
 */
public class JpClientes extends javax.swing.JPanel {

    /**
     * Creates new form JpClientes
     */
    String clientes[][];
    String numeros[][]; //Arreglo utilizado para guardar las consultas.
    DefaultTableModel modelo;
    int seleccion;
    String numcel,nombre, ciudad;
    BaseDatosClientes a;
    
    public JpClientes() {
        initComponents();
        
        a= new BaseDatosClientes();
        verTodos();
        verNumeros();
        
        
    }
    private void verTodos(){
       clientes =a.buscarClientes("Todos","Nada");
       generarTabla();
    }
    private void verNumeros(){
       clientes= a.buscarClientes("Todos", "Nada");
        for (String cliente : clientes[0]) {
            System.out.print(cliente + "\n");
        }
       System.out.print(clientes[0].length);
   }
   
    //Metodo que genera una nueva tabla con nuevos datos.(Actualiza la vista de la tabla)
    //Se tienen que crear un nuevo modelo en cada consulta para que los registros se "limpien" en cada consulta
    //Si se usa un solo modelo, los resultados de las nuevas consultas se insertan debajo de los viejos resultados.
    private void generarTabla(){
        //Se crea un nuevo modelo de tabla
        modelo = new DefaultTableModel();
        //Se agregan las columnas
        modelo.setColumnIdentifiers(new Object[]{"Nombre","Celular","Ciudad"});
        //Se agregan las filas. 
        for(int x=0;x<clientes[0].length;x++){
            modelo.addRow(new Object[]{""+clientes[1][x],""+clientes[0][x],""+clientes[2][x]});
        }
        //Se añade el nuevo modelo a la tabla
        TablaDatos.setModel(modelo);
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDatos = new rojerusan.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        BarraBusqueda = new javax.swing.JTextField();
        ButtonBuscar1 = new javax.swing.JButton();
        ButtonRegistrar = new org.edisoncor.gui.panel.PanelImage();
        labelRegistrar = new javax.swing.JLabel();
        ButtonVerTodos = new org.edisoncor.gui.panel.PanelImage();
        labelVertodos = new javax.swing.JLabel();
        ButtonModificar = new org.edisoncor.gui.panel.PanelImage();
        labelRegistrarpedido = new javax.swing.JLabel();
        ButtonEliminar = new org.edisoncor.gui.panel.PanelImage();
        labelEliminar = new javax.swing.JLabel();
        ButtonModificar1 = new org.edisoncor.gui.panel.PanelImage();
        labelModificar1 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(29, 29, 29));
        setEnabled(false);
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(646, 517));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(29, 29, 29));
        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        TablaDatos.setForeground(new java.awt.Color(29, 29, 29));
        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaDatos.setColorBackgoundHead(new java.awt.Color(59, 59, 59));
        TablaDatos.setColorFilasBackgound2(new java.awt.Color(227, 227, 227));
        TablaDatos.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        TablaDatos.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        TablaDatos.setColorSelBackgound(new java.awt.Color(153, 153, 255));
        TablaDatos.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        TablaDatos.setFuenteFilas(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TablaDatos.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TablaDatos.setFuenteHead(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        TablaDatos.setGridColor(new java.awt.Color(255, 255, 255));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaDatos);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 750, 204));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clientes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 11, 152, 22));
        add(BarraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 14, 142, -1));

        ButtonBuscar1.setText("BUSCAR");
        ButtonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscar1ActionPerformed(evt);
            }
        });
        add(ButtonBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 13, 72, -1));

        ButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button.png"))); // NOI18N
        ButtonRegistrar.setPreferredSize(new java.awt.Dimension(152, 49));
        ButtonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonRegistrarMouseClicked(evt);
            }
        });

        labelRegistrar.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 18)); // NOI18N
        labelRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        labelRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistrar.setText("Registrar");
        labelRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ButtonRegistrarLayout = new javax.swing.GroupLayout(ButtonRegistrar);
        ButtonRegistrar.setLayout(ButtonRegistrarLayout);
        ButtonRegistrarLayout.setHorizontalGroup(
            ButtonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        ButtonRegistrarLayout.setVerticalGroup(
            ButtonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        add(ButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 160, -1));

        ButtonVerTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button.png"))); // NOI18N
        ButtonVerTodos.setPreferredSize(new java.awt.Dimension(152, 49));
        ButtonVerTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonVerTodosMouseClicked(evt);
            }
        });

        labelVertodos.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 18)); // NOI18N
        labelVertodos.setForeground(new java.awt.Color(255, 255, 255));
        labelVertodos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVertodos.setText("Ver Todos");
        labelVertodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVertodosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ButtonVerTodosLayout = new javax.swing.GroupLayout(ButtonVerTodos);
        ButtonVerTodos.setLayout(ButtonVerTodosLayout);
        ButtonVerTodosLayout.setHorizontalGroup(
            ButtonVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonVerTodosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVertodos, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        ButtonVerTodosLayout.setVerticalGroup(
            ButtonVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonVerTodosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVertodos, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(ButtonVerTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 160, 50));

        ButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button.png"))); // NOI18N
        ButtonModificar.setPreferredSize(new java.awt.Dimension(152, 49));
        ButtonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonModificarMouseClicked(evt);
            }
        });

        labelRegistrarpedido.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 18)); // NOI18N
        labelRegistrarpedido.setForeground(new java.awt.Color(255, 255, 255));
        labelRegistrarpedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistrarpedido.setText("RegistrarPedido");
        labelRegistrarpedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistrarpedidoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ButtonModificarLayout = new javax.swing.GroupLayout(ButtonModificar);
        ButtonModificar.setLayout(ButtonModificarLayout);
        ButtonModificarLayout.setHorizontalGroup(
            ButtonModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRegistrarpedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ButtonModificarLayout.setVerticalGroup(
            ButtonModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRegistrarpedido, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(ButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 160, 50));

        ButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button.png"))); // NOI18N
        ButtonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonEliminarMouseClicked(evt);
            }
        });

        labelEliminar.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 18)); // NOI18N
        labelEliminar.setForeground(new java.awt.Color(255, 255, 255));
        labelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEliminar.setText("Eliminar");
        labelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ButtonEliminarLayout = new javax.swing.GroupLayout(ButtonEliminar);
        ButtonEliminar.setLayout(ButtonEliminarLayout);
        ButtonEliminarLayout.setHorizontalGroup(
            ButtonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        ButtonEliminarLayout.setVerticalGroup(
            ButtonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(ButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 160, 50));

        ButtonModificar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button.png"))); // NOI18N
        ButtonModificar1.setPreferredSize(new java.awt.Dimension(152, 49));
        ButtonModificar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonModificar1MouseClicked(evt);
            }
        });

        labelModificar1.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 18)); // NOI18N
        labelModificar1.setForeground(new java.awt.Color(255, 255, 255));
        labelModificar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModificar1.setText("Modificar");
        labelModificar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModificar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ButtonModificar1Layout = new javax.swing.GroupLayout(ButtonModificar1);
        ButtonModificar1.setLayout(ButtonModificar1Layout);
        ButtonModificar1Layout.setHorizontalGroup(
            ButtonModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonModificar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelModificar1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        ButtonModificar1Layout.setVerticalGroup(
            ButtonModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelModificar1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(ButtonModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 160, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscar1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ButtonBuscar1ActionPerformed

    private void ButtonVerTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonVerTodosMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ButtonVerTodosMouseClicked

    private void ButtonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRegistrarMouseClicked
        // TODO add your handling code here:
        Registar_clientesDialog dialogclientes =new Registar_clientesDialog(new javax.swing.JFrame(), true);
        dialogclientes.setLocationRelativeTo(null);
        dialogclientes.setVisible(true);
    }//GEN-LAST:event_ButtonRegistrarMouseClicked

    private void ButtonModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonModificarMouseClicked
        
    }//GEN-LAST:event_ButtonModificarMouseClicked

    private void ButtonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEliminarMouseClicked
        
    }//GEN-LAST:event_ButtonEliminarMouseClicked

    private void labelVertodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVertodosMouseClicked
        // TODO add your handling code here:
        verTodos();
    }//GEN-LAST:event_labelVertodosMouseClicked

    private void labelRegistrarpedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrarpedidoMouseClicked
            //llama a dialog de ciclo  
            if (TablaDatos.getSelectedRow() != -1) {
                //seleccionamos el dato 1 de la fila y lo pasamos a numcel
                
                // Convocamos al dialog de ciclos y pasamos el numcel
                Pregunta_cicloDialog dialogciclos =new Pregunta_cicloDialog(new javax.swing.JFrame(), true);
                dialogciclos.recibirDatos(numcel, nombre);
                dialogciclos.setLocationRelativeTo(null);
                dialogciclos.setVisible(true);
                
            }else {
                System.out.println("Seleccione un renglon primero");
            }
            
       
    }//GEN-LAST:event_labelRegistrarpedidoMouseClicked

    private void labelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        //Obtener la fila seleccionada. 
        int fila = TablaDatos.getSelectedRow();
        if(fila!=-1)
        {
            String id=(String) modelo.getValueAt(fila,0);
            //La ventana de confirmación retorna un valor numerico equivalente a la opcion que selecciona el usuario. 
            int op=JOptionPane.showConfirmDialog(null, "Está a punto de eliminar permanentemente al empleado '"+id+"'", "Confirmar eliminacion", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            //Si confirma la eliminación, el valor de op=0
            if(op==0){
                seleccion= TablaDatos.rowAtPoint(evt.getPoint());
                 numcel = String.valueOf(TablaDatos.getValueAt(seleccion, 1));
                
                a.eliminarCliente(numcel);
                verTodos();
            }else{
                //Sí cancela la eliminacion no pasa nada
            }
        }else{
            JOptionPane.showMessageDialog(null,"Selecciona a un empleado y presiona 'Eliminar'" ,"Busqueda de empleados",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_labelEliminarMouseClicked

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
        // TODO add your handling code here:
          seleccion= TablaDatos.rowAtPoint(evt.getPoint());
          numcel= String.valueOf(TablaDatos.getValueAt(seleccion, 1));
          nombre= String.valueOf(TablaDatos.getValueAt(seleccion, 0));
          
          Pregunta_cicloDialog dialogciclos =new Pregunta_cicloDialog(new javax.swing.JFrame(), true);
          dialogciclos.recibirDatos(numcel, nombre);
          System.out.print("Impresion del método de tabla, este es el numcel:  " + numcel+ "El nombre es:"+nombre);
        
        
        
    }//GEN-LAST:event_TablaDatosMouseClicked

    private void labelRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrarMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        Registar_clientesDialog dialogclientes =new Registar_clientesDialog(new javax.swing.JFrame(), true);
        dialogclientes.setLocationRelativeTo(null);
        dialogclientes.setVisible(true);
    }//GEN-LAST:event_labelRegistrarMouseClicked

    private void labelModificar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelModificar1MouseClicked

    private void ButtonModificar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonModificar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonModificar1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraBusqueda;
    private javax.swing.JButton ButtonBuscar1;
    private org.edisoncor.gui.panel.PanelImage ButtonEliminar;
    private org.edisoncor.gui.panel.PanelImage ButtonModificar;
    private org.edisoncor.gui.panel.PanelImage ButtonModificar1;
    private org.edisoncor.gui.panel.PanelImage ButtonRegistrar;
    private org.edisoncor.gui.panel.PanelImage ButtonVerTodos;
    private rojerusan.RSTableMetro TablaDatos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelEliminar;
    private javax.swing.JLabel labelModificar1;
    private javax.swing.JLabel labelRegistrar;
    private javax.swing.JLabel labelRegistrarpedido;
    private javax.swing.JLabel labelVertodos;
    // End of variables declaration//GEN-END:variables
}
