/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.sheintap;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class JpVerTodos extends javax.swing.JPanel {

    /**
     * Creates new form JpVerTodos
     */
    BaseDatosVerTodos v;//Declaración del objeto de uso global
    String[][] consultaVacaciones; //Declaracion de arreglo que guarda los resultados de cualquier consulta. 
    DefaultTableModel modelo; //Declaracion del modelo de la tabla de uso global.
    public JpVerTodos() {
        initComponents();
        v = new BaseDatosVerTodos();
        verTodos();
    }
    
    private void generarTabla(){
        //Se crea un nuevo modelo de tabla
        modelo = new DefaultTableModel();
        //Se agregan las columnas
        modelo.setColumnIdentifiers(new Object[]{"Numero Celular","Nombre del Articulo","Talla", "Precio", "Estado"});
        //Se agregan las filas. 
        for(int x=0;x<consultaVacaciones[0].length;x++){
            modelo.addRow(new Object[]{consultaVacaciones[0][x],consultaVacaciones[1][x],consultaVacaciones[2],consultaVacaciones[3],consultaVacaciones[4]});
        }
        //Se añade el nuevo modelo a la tabla
        TablaDatos.setModel(modelo);
       
    }
     private void verTodos(){
        consultaVacaciones =v.buscarTodos("Todos");
        generarTabla();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new rojerusan.RSTableMetro();

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSTableMetro TablaDatos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
