/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.sheintap;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Pregunta_clientesdialog extends javax.swing.JDialog {

    /**
     * Creates new form Pregunta_clientesdialog
     */
    String consultapedidos[][]; //Arreglo que se encarga de guardar consultas.
    String nompuesto[][];
    
    DefaultTableModel modelo;
    int seleccion;
    public Pregunta_clientesdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRegistrado = new javax.swing.JButton();
        buttonNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonRegistrado.setText("Cliente registrado");
        buttonRegistrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRegistradoMouseClicked(evt);
            }
        });

        buttonNuevo.setText("Cliente nuevo");
        buttonNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNuevoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(buttonRegistrado)
                .addGap(49, 49, 49)
                .addComponent(buttonNuevo)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRegistrado)
                    .addComponent(buttonNuevo))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegistradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegistradoMouseClicked
        // TODO add your handling code here:
        Registrar_pedidosDialog pedidos=new Registrar_pedidosDialog(new javax.swing.JFrame(), true);
        pedidos.setLocationRelativeTo(null);
        pedidos.setVisible(true);
        
    }//GEN-LAST:event_buttonRegistradoMouseClicked

    private void buttonNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNuevoMouseClicked
        // TODO add your handling code here:
        Registar_clientesDialog dialogclientes =new Registar_clientesDialog(new javax.swing.JFrame(), true);
        dialogclientes.setLocationRelativeTo(null);
        dialogclientes.setVisible(true);
        Registrar_pedidosDialog pedidos=new Registrar_pedidosDialog(new javax.swing.JFrame(), true);
        pedidos.setLocationRelativeTo(null);
        pedidos.setVisible(true);
        
        
    }//GEN-LAST:event_buttonNuevoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pregunta_clientesdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pregunta_clientesdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pregunta_clientesdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pregunta_clientesdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pregunta_clientesdialog dialog = new Pregunta_clientesdialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNuevo;
    private javax.swing.JButton buttonRegistrado;
    // End of variables declaration//GEN-END:variables
}
