/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.sheintap;

import javax.swing.JOptionPane;


/**
 *
 * @author Administrator
 */

public class Registrar_pedidosDialog extends javax.swing.JDialog {

    /**
    
     */
    String clientes[][];
    String clientes2[][];
    

    String numcel, nom_art, talla, nociclo, precio, opc, color, nombre;
   ;
    BaseDatosPedidosPendientes a;
    BaseDatosClientes b;
    public Registrar_pedidosDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        a = new BaseDatosPedidosPendientes();
        b= new BaseDatosClientes();
        
        initComponents();
        
        
        
    }
    public void recibirdatos(String numcel,  String nociclo, String nom ){
        this.numcel= numcel;
        this.nociclo= nociclo;
        this.nombre= nom;
        labelnombre.setText(nom);
        labelnumcel.setText(numcel);
        textfieldNociclo.setText(nociclo);
    }
     private void InsertarCombobox(){
       clientes2= b.buscarClientes("Todos", "Nada");
        for (String item : clientes2[0]) {
            
        }
        
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textfieldNombreart = new javax.swing.JTextField();
        buttonjdRegistrarpedido = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textfieldNociclo = new javax.swing.JTextField();
        textfieldPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboboxEstado = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        textfieldColor = new javax.swing.JTextField();
        labelnumcel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelnombre = new javax.swing.JLabel();
        comboboxTalla = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 11)); // NOI18N
        jLabel1.setText("Registrar pedido");

        jLabel2.setText("Numero celular");

        jLabel3.setText("Nombre articulo");

        jLabel4.setText("Talla");

        textfieldNombreart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNombreartActionPerformed(evt);
            }
        });

        buttonjdRegistrarpedido.setText("Registrar");
        buttonjdRegistrarpedido.setActionCommand("Actuaiizar");
        buttonjdRegistrarpedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonjdRegistrarpedidoMouseClicked(evt);
            }
        });

        jLabel5.setText("No Ciclo");

        jLabel6.setText("Precio");

        jLabel7.setText("Estado");

        comboboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Incompleto", "Completo" }));
        comboboxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxEstadoActionPerformed(evt);
            }
        });

        jLabel8.setText("Color");

        jLabel9.setText("Nombre");

        comboboxTalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL", "ÚNICO", "0XL", "1XL", "2XL", "3XL", "4XL" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(buttonjdRegistrarpedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfieldNociclo)
                            .addComponent(textfieldPrecio)
                            .addComponent(comboboxEstado, 0, 153, Short.MAX_VALUE)
                            .addComponent(labelnumcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textfieldNombreart, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textfieldColor)
                            .addComponent(labelnombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboboxTalla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labelnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelnumcel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textfieldNombreart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboboxTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldNociclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(buttonjdRegistrarpedido)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonjdRegistrarpedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonjdRegistrarpedidoMouseClicked
        // TODO add your handling code here:
        //numcel= comboboxClientes.getSelectedItem().toString();
        
        nom_art= textfieldNombreart.getText();
        talla= comboboxTalla.getSelectedItem().toString();
        nociclo= textfieldNociclo.getText();
        precio= textfieldPrecio.getText();
        color= textfieldColor.getText();
        
        //Verifica que el precio sea siempre numeros para castear  
        try{
            int num= Integer.parseInt(precio);
            // TODO add your handling code here:
            if("Completado".equals(comboboxEstado.getSelectedItem().toString())){
                opc= "Completado";
            }else{
                opc="Incompleto";
            }
            //Verifica en qué estado está el pedido
            if("Incompleto".equals(opc)){
                System.out.print(nociclo);
                a.insertarPedido(numcel, nom_art, talla, nociclo, precio, color, nombre);
                
                textfieldNombreart.setText("");
                
            }else{
               
            }
        }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, e, talla, WIDTH);
        }
                
                
        
        
    }//GEN-LAST:event_buttonjdRegistrarpedidoMouseClicked

    private void comboboxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxEstadoActionPerformed
        // TODO add your handling code here:
        if("Incompleto".equals(comboboxEstado.getSelectedItem().toString())){
            opc= "Incompleto";
        }else{
            opc="Completo";
        }
        System.out.print(opc);
    }//GEN-LAST:event_comboboxEstadoActionPerformed

    private void textfieldNombreartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNombreartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNombreartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_pedidosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_pedidosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_pedidosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_pedidosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Registrar_pedidosDialog dialog = new Registrar_pedidosDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonjdRegistrarpedido;
    private javax.swing.JComboBox<String> comboboxEstado;
    private javax.swing.JComboBox<String> comboboxTalla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelnombre;
    private javax.swing.JLabel labelnumcel;
    private javax.swing.JTextField textfieldColor;
    private javax.swing.JTextField textfieldNociclo;
    private javax.swing.JTextField textfieldNombreart;
    private javax.swing.JTextField textfieldPrecio;
    // End of variables declaration//GEN-END:variables
}
